import type { Tourist, CityVisit, TouristWithVisits } from "@shared/schema";

export const MOCK_ENTITY_ID = "999";
export const MOCK_ENTITY_TYPE_ID = "176";
export const MOCK_EVENT_TITLE = "Тестовый тур: Пекин - Шанхай (Март 2025)";

export const mockTourists: Tourist[] = [
  {
    id: "1",
    entityId: MOCK_ENTITY_ID,
    entityTypeId: MOCK_ENTITY_TYPE_ID,
    name: "Иванов Иван Иванович",
    email: "ivanov@example.com",
    phone: "+7 (999) 123-45-67",
    passport: "123456789",
    birthDate: "1985-03-15",
    surcharge: "5000 руб",
    nights: "14",
    bitrixContactId: "1001",
    bitrixDealId: "5001",
  },
  {
    id: "2",
    entityId: MOCK_ENTITY_ID,
    entityTypeId: MOCK_ENTITY_TYPE_ID,
    name: "Петрова Мария Сергеевна",
    email: "petrova@example.com",
    phone: "+7 (999) 234-56-78",
    passport: "987654321",
    birthDate: "1990-07-22",
    surcharge: "3000 руб",
    nights: "12",
    bitrixContactId: "1002",
    bitrixDealId: "5001",
  },
  {
    id: "3",
    entityId: MOCK_ENTITY_ID,
    entityTypeId: MOCK_ENTITY_TYPE_ID,
    name: "Сидоров Петр Александрович",
    email: "sidorov@example.com",
    phone: "+7 (999) 345-67-89",
    passport: "456789123",
    birthDate: "1978-11-08",
    surcharge: "",
    nights: "14",
    bitrixContactId: "1003",
    bitrixDealId: "5002",
  },
  {
    id: "4",
    entityId: MOCK_ENTITY_ID,
    entityTypeId: MOCK_ENTITY_TYPE_ID,
    name: "Козлова Анна Дмитриевна",
    email: "kozlova@example.com",
    phone: "+7 (999) 456-78-90",
    passport: "321654987",
    birthDate: "1995-05-30",
    surcharge: "2500 руб",
    nights: "10",
    bitrixContactId: "1004",
    bitrixDealId: "5002",
  },
  {
    id: "5",
    entityId: MOCK_ENTITY_ID,
    entityTypeId: MOCK_ENTITY_TYPE_ID,
    name: "Морозов Дмитрий Викторович",
    email: "morozov@example.com",
    phone: "+7 (999) 567-89-01",
    passport: "654321789",
    birthDate: "1982-09-12",
    surcharge: "7500 руб",
    nights: "16",
    bitrixContactId: "1005",
    bitrixDealId: "5003",
  },
  {
    id: "6",
    entityId: MOCK_ENTITY_ID,
    entityTypeId: MOCK_ENTITY_TYPE_ID,
    name: "Новикова Елена Павловна",
    email: "",
    phone: "",
    passport: "",
    birthDate: "",
    surcharge: "",
    nights: "",
    bitrixContactId: "",
    bitrixDealId: "",
  },
];

export const mockItineraries: CityVisit[] = [
  // Иванов - полный маршрут по всем городам
  {
    id: "101",
    touristId: "1",
    city: "beijing",
    arrivalDate: "2025-03-10",
    arrivalTime: "14:30",
    departureDate: "2025-03-13",
    departureTime: "09:00",
    transportType: "plane",
    flightNumber: "SU212",
    airport: "PEK",
    transfer: "Отель → Аэропорт",
    hotelName: "Beijing Grand Hotel",
    roomType: "twin",
    departureTransportType: "train",
    departureFlightNumber: "G101",
    departureAirport: "",
    departureTransfer: "Отель → Вокзал",
  },
  {
    id: "102",
    touristId: "1",
    city: "luoyang",
    arrivalDate: "2025-03-13",
    arrivalTime: "15:20",
    departureDate: "2025-03-15",
    departureTime: "10:30",
    transportType: "train",
    flightNumber: "G101",
    airport: "",
    transfer: "Вокзал → Отель",
    hotelName: "Luoyang Peony Hotel",
    roomType: "double",
    departureTransportType: "train",
    departureFlightNumber: "D222",
    departureAirport: "",
    departureTransfer: "",
  },
  {
    id: "103",
    touristId: "1",
    city: "xian",
    arrivalDate: "2025-03-15",
    arrivalTime: "13:45",
    departureDate: "2025-03-18",
    departureTime: "08:15",
    transportType: "train",
    flightNumber: "D222",
    airport: "",
    transfer: "",
    hotelName: "Xi'an Dynasty Hotel",
    roomType: "twin",
    departureTransportType: "plane",
    departureFlightNumber: "CA1234",
    departureAirport: "XIY",
    departureTransfer: "Отель → Аэропорт",
  },
  {
    id: "104",
    touristId: "1",
    city: "zhangjiajie",
    arrivalDate: "2025-03-18",
    arrivalTime: "16:00",
    departureDate: "2025-03-20",
    departureTime: "11:00",
    transportType: "plane",
    flightNumber: "CA1234",
    airport: "DYG",
    transfer: "Аэропорт → Отель",
    hotelName: "Zhangjiajie Mountain View Resort",
    roomType: "double",
    departureTransportType: "plane",
    departureFlightNumber: "MU5678",
    departureAirport: "DYG",
    departureTransfer: "Отель → Аэропорт",
  },
  {
    id: "105",
    touristId: "1",
    city: "shanghai",
    arrivalDate: "2025-03-20",
    arrivalTime: "18:30",
    departureDate: "2025-03-24",
    departureTime: "12:00",
    transportType: "plane",
    flightNumber: "MU5678",
    airport: "PVG",
    transfer: "Аэропорт → Отель",
    hotelName: "Shanghai Bund Hotel",
    roomType: "twin",
    departureTransportType: "plane",
    departureFlightNumber: "SU213",
    departureAirport: "PVG",
    departureTransfer: "Отель → Аэропорт",
  },

  // Петрова - частичный маршрут
  {
    id: "201",
    touristId: "2",
    city: "beijing",
    arrivalDate: "2025-03-10",
    arrivalTime: "14:30",
    departureDate: "2025-03-13",
    departureTime: "09:00",
    transportType: "plane",
    flightNumber: "SU212",
    airport: "PEK",
    transfer: "Аэропорт → Отель",
    hotelName: "Beijing Grand Hotel",
    roomType: "double",
    departureTransportType: "train",
    departureFlightNumber: "G101",
    departureAirport: "",
    departureTransfer: "",
  },
  {
    id: "202",
    touristId: "2",
    city: "xian",
    arrivalDate: "2025-03-15",
    arrivalTime: "13:45",
    departureDate: "2025-03-18",
    departureTime: "08:15",
    transportType: "train",
    flightNumber: "D222",
    airport: "",
    transfer: "",
    hotelName: "Xi'an Dynasty Hotel",
    roomType: "double",
    departureTransportType: "plane",
    departureFlightNumber: "CA1234",
    departureAirport: "XIY",
    departureTransfer: "",
  },
  {
    id: "203",
    touristId: "2",
    city: "shanghai",
    arrivalDate: "2025-03-20",
    arrivalTime: "18:30",
    departureDate: "2025-03-22",
    departureTime: "12:00",
    transportType: "plane",
    flightNumber: "MU5678",
    airport: "PVG",
    transfer: "Аэропорт → Отель",
    hotelName: "Shanghai Bund Hotel",
    roomType: "double",
    departureTransportType: "plane",
    departureFlightNumber: "SU213",
    departureAirport: "PVG",
    departureTransfer: "Отель → Аэропорт",
  },

  // Сидоров
  {
    id: "301",
    touristId: "3",
    city: "beijing",
    arrivalDate: "2025-03-11",
    arrivalTime: "10:00",
    departureDate: "2025-03-14",
    departureTime: "",
    transportType: "plane",
    flightNumber: "SU214",
    airport: "PEK",
    transfer: "",
    hotelName: "Beijing Central Hotel",
    roomType: "twin",
    departureTransportType: "train",
    departureFlightNumber: "",
    departureAirport: "",
    departureTransfer: "",
  },
  {
    id: "302",
    touristId: "3",
    city: "luoyang",
    arrivalDate: "2025-03-14",
    arrivalTime: "",
    departureDate: "2025-03-16",
    departureTime: "",
    transportType: "train",
    flightNumber: "",
    airport: "",
    transfer: "",
    hotelName: "Luoyang Peony Hotel",
    roomType: "twin",
    departureTransportType: "",
    departureFlightNumber: "",
    departureAirport: "",
    departureTransfer: "",
  },

  // Козлова
  {
    id: "401",
    touristId: "4",
    city: "beijing",
    arrivalDate: "2025-03-11",
    arrivalTime: "10:00",
    departureDate: "2025-03-14",
    departureTime: "",
    transportType: "plane",
    flightNumber: "SU214",
    airport: "PEK",
    transfer: "",
    hotelName: "Beijing Central Hotel",
    roomType: "double",
    departureTransportType: "",
    departureFlightNumber: "",
    departureAirport: "",
    departureTransfer: "",
  },
  {
    id: "402",
    touristId: "4",
    city: "shanghai",
    arrivalDate: "2025-03-20",
    arrivalTime: "18:30",
    departureDate: "2025-03-23",
    departureTime: "12:00",
    transportType: "plane",
    flightNumber: "MU5678",
    airport: "PVG",
    transfer: "",
    hotelName: "Shanghai Garden Hotel",
    roomType: "double",
    departureTransportType: "plane",
    departureFlightNumber: "SU213",
    departureAirport: "PVG",
    departureTransfer: "",
  },

  // Морозов - только один город
  {
    id: "501",
    touristId: "5",
    city: "shanghai",
    arrivalDate: "2025-03-20",
    arrivalTime: "18:30",
    departureDate: "2025-03-26",
    departureTime: "12:00",
    transportType: "plane",
    flightNumber: "MU5678",
    airport: "PVG",
    transfer: "Аэропорт → Отель",
    hotelName: "Shanghai Luxury Suites",
    roomType: "twin",
    departureTransportType: "plane",
    departureFlightNumber: "SU213",
    departureAirport: "PVG",
    departureTransfer: "Отель → Аэропорт",
  },
];

// Связываем маршруты с туристами
export function getMockTouristsWithItineraries(): TouristWithVisits[] {
  return mockTourists.map(tourist => ({
    ...tourist,
    visits: mockItineraries.filter(it => it.touristId === tourist.id),
  }));
}
